# Generated by Django 4.1.6 on 2024-01-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nitrogen', models.CharField(max_length=10)),
                ('Phosphorous', models.CharField(max_length=10)),
                ('Potassium', models.CharField(max_length=10)),
                ('Temperature', models.CharField(max_length=10)),
                ('Humidity', models.CharField(max_length=10)),
                ('Ph', models.CharField(max_length=10)),
                ('Rainfall', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=10)),
            ],
        ),
    ]
