# Generated by Django 4.1.6 on 2024-01-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croprecommendation',
            name='Humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='Nitrogen',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='Ph',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='Phosphorous',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='Potassium',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='Rainfall',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='Temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='label',
            field=models.CharField(max_length=50),
        ),
    ]
