# Generated by Django 4.1.6 on 2024-01-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0003_alter_croprecommendation_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croprecommendation',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
